package il.ac.technion.cs.smarthouse.applications.shutter;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class shutter_app_uiController {
	@FXML
	private Button openButton;
	@FXML
	private Button closeButton;
	@FXML
	private Button autoButton;
	@FXML
	private TextField fromField;
	@FXML
	private TextField toField;

	// Event Listener on Button[#openButton].onAction
	@FXML
	public void openClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#closeButton].onAction
	@FXML
	public void closeClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#autoButton].onAction
	@FXML
	public void autoClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
